### ISSUE TITLE
varapp development

### ISSUE THREAD

**Issue by aurelBZH** [varapp/varapp-frontend-react#3]
hi julien,

At the bioinformatic plateform of the brain and spine institute. We are looking for a graphical user interface for genomic filtering. We are very interesting by Varapp. Is the development still in progress ?

thanks
Aurélien Béliard 
Bioinformatics engineer

**Comment by jdelafon** [comment]
Hi Aurelien,

Thank you for your intersest.
The product is ready for production and in use, but development is currently on hold. 
If there is interest and enough resources, there is no reason not to reopen it, though. I would be happy to see it updated.
Since I left the company, I am no more participating to this project. I suggest that you contact the project manager for more details:
sylvain.pradervand @ unil.ch
